# Generated by Django 5.2.3 on 2025-07-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tg_chat_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Телеграм chat_id"
            ),
        ),
    ]
