# Generated by Django 5.2.3 on 2025-07-09 20:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.CharField(max_length=100, verbose_name='Вознаграждение')),
            ],
            options={
                'verbose_name': 'Вознаграждение',
                'verbose_name_plural': 'Вознаграждения',
            },
        ),
        migrations.CreateModel(
            name='HabitLinked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100, verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Связанная привычка',
                'verbose_name_plural': 'Связанные привычки',
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=100, verbose_name='Действие')),
                ('time', models.TimeField(verbose_name='Время начала действия')),
                ('location', models.CharField(max_length=100, verbose_name='Место выполнения')),
                ('frequency', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Периодичность')),
                ('time_unit', models.CharField(choices=[('days', 'дни'), ('minutes', 'минуты'), ('seconds', 'секунды')], default='minutes', max_length=15, verbose_name='Единица времени')),
                ('implementation_time', models.PositiveIntegerField(db_index=True, default=2, verbose_name='Время выполнения')),
                ('is_public', models.BooleanField(default=True)),
                ('award', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='habits.award')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
