name: Django CI

on: [ push, pull_request ]

env:
  DJANGO_SETTINGS_MODULE: 'config.settings'
  DATABASE_NAME: 'test_db'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: |
          pip install flake8
          flake8 .

  test:
    runs-on: ubuntu-latest
    needs: lint

    env:
      DATABASE_NAME: ':memory:'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test --noinput

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up SSH
        uses: shimataro/ssh-key-action@v2
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy
        run: |
          rsync -avz --exclude '__pycache__' . ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.DEPLOY_DIR }}
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
            cd ${{ secrets.DEPLOY_DIR }}
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart myapp.service
          "