# Generated by Django 5.2.3 on 2025-07-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="user",
            new_name="owner",
        ),
    ]
